# Generated by Django 4.0.2 on 2022-02-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=250, verbose_name='URL')),
                ('NumberOfShows', models.IntegerField(verbose_name='NumberOfShows')),
                ('categories', models.CharField(max_length=250, verbose_name='Categories')),
            ],
        ),
    ]
